name: main
on:
# push:
 #   branches:
    #  - main
 workflow_dispatch:

jobs:

  job1:
    #performance_test:
    name: ExecutingFileRead
    
     # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"
    
    runs-on: ubuntu-latest
    outputs:
      VUSERSSS: ${{ steps.variablevalue.outputs.VUSERSSS }}
      VITERATION: ${{ steps.variablevalue.outputs.VITERATION }}
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it    
      - name: Read File
        id: package
        uses: jaywcjlove/github-action-read-file@main
        with:
         path: TestParameters.txt

      - name: Echo TestParameters.txt
        id: variablevalue
        run: |
         value="${{ steps.package.outputs.content }}"
         userss=`echo "$value" | awk -F "," '{print $1}'` >> $GITHUB_ENV
         echo "$userss"
         echo "VUSERSSS=$userss" >> $GITHUB_OUTPUT
         iterationn=`echo "$value" | awk -F "," '{print $2}'` >> $GITHUB_ENV
         echo "$iterationn"
         echo "VITERATION=$iterationn" >> $GITHUB_OUTPUT

  job2:
  
    name: values stored 
    needs: job1
    runs-on: ubuntu-latest
    env:
          VUSERSSS: ${{ needs.job1.outputs.VUSERSSS }}
          VITERATION: ${{ needs.job1.outputs.VITERATION }}
    steps:

         - name: values
         - uses: peter-evans/repository-dispatch@v1
         - with:
            token: ${{ secrets.PAT_TOKEN }}
            event-type: my-event
            client-payload: '{"VUSERSSS": "${{ env.VUSERSSS }}", "VITERATION": "${{ env.VITERATION }}"}'

  job3:
       name: trigger_sanity_test_workflow
       needs: job2
       runs-on: ubuntu-latest
       steps:
        - name: Trigger Sanity Test Work Flow
          run: |
           curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/telus/TIDS_Performance_Jmeter/actions/workflows/jmeter.yml/dispatches \
            -d '{"ref":"main"}'
